In [2]:
import numpy as np
import random

In [8]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
T = np.random.randint(-2,3, size=(2,2))
T

array([[-2, -2],
       [ 1,  0]])

Particular Matrices

* Identity Matrix

In [6]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


* Zeros

In [7]:
Z = np.zeros((3,3)) # dimensions here must be in a tuple
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* Ones

In [4]:
O = np.ones((5,4)) # dimensions must be passed as tuple
print(O)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


* Diagonal Matrix

In [6]:
D = np.diag([1,2,3])
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [10]:
C = np.diag(M) # np.diag can either create a matrix from a list (of the diag) or create a list of the diag elements (from a matrix)
print(C)

[1 5 9]
